
name: CI

on:
  push: 
    branches: [ main ]
    tags:
    - '*'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
    execute-gut:
      name: Run GUT tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Docker test
          uses: ceceppa/godot-gut-ci@main
          with:
            godot_version: 4.1.2 # uses godot 4.1.2
            gut_params: -gdir=res://test/unit -gsuffix=.gd -gprefix=test_

    build:
      needs: execute-gut
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v3
        - name: exportGame
          uses: firebelley/godot-export@v5.2.1
          with: 
            godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.1.2-stable/Godot_v4.1.2-stable_linux.x86_64.zip
            godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.1.2-stable/Godot_v4.1.2-stable_export_templates.tpz
            relative_project_path: ./
            relative_export_path: ./build
            archive_output: true
        - name: create release
          uses: ncipollo/release-action@v1.13.0
          with:
            skipIfReleaseExists: true
            tag: "v0.0.1"
            commit: "main"
