
name: CI

on:
  push: 
    branches: [ main ]
    tags:
    - '*'
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

    unitTests:
      runs-on: ubuntu-latest  # You can choose a different runner if needed

      steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Godot
        run: |
          wget https://github.com/godotengine/godot-builds/releases/download/4.1.2-stable/Godot_v4.1.2-stable_linux.x86_64.zip
          unzip Godot_v4.1.2-stable_linux.x86_64.zip
        working-directory: ./  # Navigate to your project directory

      - name: Run unit tests
        run: |
          ./Godot_v4.1.2-stable_linux.x86_64 --rendering-driver opengl3 --script addons/gut/gut_cmdln.gd -d --path $PWD -ginclude_subdirs -gdir=res://Tests -gexit -gprefix=test_
        working-directory: ./

    build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:

        - uses: actions/checkout@v3
        - name: exportGame
          uses: firebelley/godot-export@v5.2.1
          with: 
            godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.1.2-stable/Godot_v4.1.2-stable_linux.x86_64.zip
            godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.1.2-stable/Godot_v4.1.2-stable_export_templates.tpz
            relative_project_path: ./
            relative_export_path: ./build
            archive_output: true
            
        - name: create release
          uses: ncipollo/release-action@v1.13.0
          with:
            skipIfReleaseExists: true
            tag: "v0.0.1"
            commit: "main"
