
name: CI

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

    build:

      runs-on: windows-latest

      steps:

        - uses: actions/checkout@v3
        - name: exportGame
          uses: firebelley/godot-export@v5.2.1
          with: 
            godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.1.2-stable/Godot_v4.1.2-stable_win64.exe.zip
            godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.1.2-stable/Godot_v4.1.2-stable_export_templates.tpz
            relative_project_path: ./
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
